### ISSUE TITLE
Histogram crashes on applying filters if filter column used in plot

### ISSUE THREAD

**Issue by dani2112** [Renumics/spotlight#81] opened 2023-06-02 11:35 UTC
**Describe the bug**
Plotting histogram in spotlight, filtering according to a column that is used in the histogram view, then hitting "hide unfiltered" will result in error rendering component.

**To Reproduce**
See above.

**Expected behavior**
The histogram should be filtered according to the currently active filter without crashing.

**Screenshots**
![Screenshot from 2023-06-02 13-34-16](https://github.com/Renumics/spotlight/assets/6371429/e13c68dd-9291-46fb-a5a5-c34de2b0f58d)

**Desktop (please complete the following information):**

-   OS: Ubuntu 20.04
-   Browser Chrome
-   Browser Version 114.0.5735.90 (Official Build) (64-bit)
-   Spotlight Version 1.0.0

**Additional context**
-

**Comment by steffenslavetinsky** [comment] 2023-06-02 11:41
This might be a potential duplicate of #28 

Could you verify if the same error also Happens on the current master?

Otherwise could you provide the error message in the Browser console?

**Comment by dani2112** [comment] 2023-06-02 11:51
Cannot reproduce on current master. Original error message was slightly different but also related to color values.

**Closed** 2023-06-02 12:03 UTC
Labels: bug
